version: "3"

services:
  stackcoin:
    build: ./.
    image: jackharrhy/stackcoin
    env_file:
      - ./.env
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - backend

  postgres:
    image: postgres:12
    env_file:
      - ./.env
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.0.3
    env_file:
      - ./.env
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - postgres

volumes:
  db:

networks:
  backend:
