version: '3'

services:
  stackcoin:
    image: jackharrhy/stackcoin
    build: ./.
    env_file:
      - ./.env
    ports:
      - 3000:3000

  postgres:
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
