module StackCoin
  EPOCH = Time.unix(1574467200)

  DEV_MODE = true # TODO make false when prod

  STACKCOIN_SITE_BASE = ENV["STACKCOIN_SITE_BASE"]
  STACKCOIN_SITE_DOMAIN = URI.parse(STACKCOIN_SITE_BASE).host

  POSTGRES_DB                     = ENV["POSTGRES_DB"]
  DATABASE_CONNECTION_STRING_BASE = ENV["STACKCOIN_DATABASE_CONNECTION_STRING_BASE"]
  DATABASE_CONNECTION_STRING      = "#{DATABASE_CONNECTION_STRING_BASE}/#{POSTGRES_DB}"
end
